# Reference: https://www.mkdocs.org/user-guide/configuration

site_name: Open Data Scotland Docs
site_url: https://docs.opendata.scot
repo_url: https://github.com/OpenDataScotland/opendata.scot_docs
docs_dir: ..\

# Metadata
site_description: #TODO
site_author: #TODO
copyright: |
            All original content
            <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>
            <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons Licence" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png"></a>
